#!/usr/bin/env bash
# configures a new Ubuntu machine with Nginx
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School for the win!" >> index.html
sudo mv index.html /var/www/html
