#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
suffix='server_name _;'
new_string='\n\tlocation /redirect_me{\n\t\treturn 301 https://www.linkedin.com/in/jordan-bonnett-gomez/;\n\t}'
sed -i "/$suffix/a\\$new_string" /etc/nginx/sites-available/default
sudo service nginx restart
