#!/usr/bin/env bash
# Configure your Load Balancer
sudo apt-get -y update
sudo apt-get install -y haproxy

sudo echo "
frontend main
        bind *:80
        mode http
        default_backend web-server

backend web-server
        balance roundrobin
        server 2858-web-01 34.138.233.200:80 check
        server 2858-web-02 104.196.8.186:80 check" >> /etc/haproxy/haproxy.cfg

echo "ENABLED=1" >> /etc/default/haproxy

sudo service haproxy restart
